title: A blog for studing
subtitle: The blog with logs for studing.
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/study_log" # the subpath of your site, e.g. /blog
url: "https://zzttt.github.io/study_log" # the base hostname & protocol for your site, e.g. http://example.com

author_logo: profile.png
disqus_shortname: sujay-kundu  #for comments using disqus
author: Armin
author_bio: Hello, This is Armin living in South Korea, working as a software engineer.
author_email: "hihijo07@gmail.com"
author_location: South Korea
author_website_url: "https://yourwebsite.com"

# social links
twitter_username: None
github_username:  arminic
facebook_username: None
linkedin_username: Armin
behance_username: Armin
instagram_username: Armin
medium_username: Armin 
telegram_username: Armin
dribbble_username: Armin 
flickr_username: Armin